[package]
name = "sens"
version = "0.1.0"
authors = ["buckn <nathanieljbuck7@gmail.com>"]
edition = "2018"

[dependencies]
web-view = "0.6.0"
serde_derive = "1.0.104"
serde_json = "1.0.48"
serde = "1.0.104"

[build-dependencies]
download_rs = "0.2.0"

[dependencies.lib_sens]
path = "../lib_sens"
